FROM golang:1.23.2-alpine3.20 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o app-mid .

FROM alpine:3.20 AS build-release-stage

WORKDIR /

RUN apk add --no-cache gcompat

COPY --from=build-stage /app/app-mid .
COPY --from=build-stage /app/.env .

RUN chmod +x /app-mid

EXPOSE 8080

ENTRYPOINT ["/app-mid"]
