version: "2.8"

services:
  postgres:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    networks:
      - backEntryMiddle
  
  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--loglevel", "warning","--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - backEntryMiddle

  app:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - backEntryMiddle

networks:
  backEntryMiddle: