openapi: 3.0.0
info:
  title: Document Management API V2
  description: API для управления документами и пользователями
  version: "2.0.0"
paths:
  /api/register:
    post:
      summary: Регистрация нового пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Токен администратора
                login:
                  type: string
                  description: Логин нового пользователя
                pswd:
                  type: string
                  description: Пароль нового пользователя
              required:
                - login
                - pswd
      responses:
        '200':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: object
                    properties:
                      login:
                        type: string
                        description: Логин зарегистрированного пользователя
        '400':
          description: Неверный запрос
          content:
            application/json:
              example:
                message: "Некорректный формат данных"
        '500':
          description: Ошибка сервера
          content:
            application/json:
              example:
                message: "Ошибка сервера"

  /api/auth:
    post:
      summary: Аутентификация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  description: Логин пользователя
                pswd:
                  type: string
                  description: Пароль пользователя
              required:
                - login
                - pswd
      responses:
        '200':
          description: Успешная аутентификация
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: object
                    properties:
                      token:
                        type: string
                        description: Токен сессиии
              example:
                response:
                  token: userToken
        '400':
          description: Неверный запрос
          content:
            application/json:
              example:
                message: "Неверный формат данных"
        '401':
          description: Неверные логин или пароль
          content:
            application/json:
              example:
                message: "Неверный логин или пароль"
        '500':
          description: Ошибка сервера
          content:
            application/json:
              example:
                message: "Ошибка сервера"

  /api/docs:
    post:
      summary: Загрузка нового документа
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                meta:
                  type: object
                  properties:
                    name:
                      type: string
                    file:
                      type: boolean
                    public:
                      type: boolean
                    mime:
                      type: string
                    grant:
                      type: array
                      items:
                        type: string             
              required:
                - meta
      parameters:
        - in: header
          name: Authorization
          required: true
          description: Токен пользователя для авторизации
          schema:
            type: string
            example: userToken
      responses:
        '200':
          description: Документ успешно загружен
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      json:
                        type: object
                      file:
                        type: string
        '400':
          description: Неверный запрос
          content:
            application/json:
              example:
                message: "Некорректный запрос"
        '401':
          description: Неавторизованный доступ
          content:
            application/json:
              example:
                message: "Необходим токен"
        '500':
          description: Ошибка сервера
          content:
            application/json:
              example:
                message: "Ошибка сервера"
    get:
      summary: Получение списка документов
      parameters:
        - in: header
          name: Authorization
          required: true
          description: Токен пользователя для авторизации
          schema:
            type: string
            example: userToken
        - in: query
          name: login
          schema:
            type: string
          description: Логин пользователя (опционально)
        - in: query
          name: key
          schema:
            type: string
          description: Имя колонки для фильтрации
        - in: query
          name: value
          schema:
            type: string
          description: Значение фильтра
        - in: query
          name: limit
          schema:
            type: integer
          description: Количество документов в списке
      responses:
        '200':
          description: Список документов
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      docs:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                            mime:
                              type: string
                            file:
                              type: boolean
                            public:
                              type: boolean
                            created:
                              type: string
                            grant:
                              type: array
                              items:
                                type: string
              example:
                data:
                  docs:
                    - id: "1"
                      name: "photo.jpg"
                      mime: "image/jpg"
                      file: true
                      public: true
                      created: "2024-11-01T12:00:00Z"
                      grant: ["login1", "login2"]
        '400':
          description: Неверный запрос
          content:
            application/json:
              example:
                message: "Некорректный запрос"
        '500':
          description: Ошибка сервера
          content:
            application/json:
              example:
                message: "Ошибка сервера"
    head:
      summary: Получение мета-данных документа
      responses:
        '200':
          description: Мета-данные успешно получены
        '400':
          description: Неверный запрос
        '500':
          description: Ошибка сервера
  /api/docs/{id}:
    get:
      summary: Получение одного документа
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: header
          name: Authorization
          required: true
          description: Токен пользователя для авторизации
          schema:
            type: string
            example: userToken
      responses:
        '200':
          description: Документ найден
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      file:
                        type: string
                      mime:
                        type: string
        '400':
          description: Неверный запрос
          content:
            application/json:
              example:
                message: "Неверный запрос"
        '401':
          description: Неавторизованный доступ
          content:
            application/json:
              example:
                message: "Необходим токен"
        '500':
          description: Ошибка сервера
          content:
            application/json:
              example:
                message: "Ошибка сервера"
    delete:
      summary: Удаление документа
      parameters:
        - in: header
          name: Authorization
          required: true
          description: Токен пользователя для авторизации
          schema:
            type: string
            example: userToken
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Документ удален
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: object
                    properties:
                      id:
                        type: string
                        description: ID удаленного документа
              example:
                response:
                  id: "1"
        '400':
          description: Неверный запрос
          content:
            application/json:
              example:
                message: "Некорректный запрос"
        '404':
          description: Документ не найден
          content:
            application/json:
              example:
                message: "Документ не найден"
        '500':
          description: Ошибка сервера
          content:
            application/json:
              example:
                message: "Ошибка сервера"
    head:
      summary: Получение мета-данных документа
      responses:
        '200':
          description: Мета-данные документа успешно получены
        '400':
          description: Неверный запрос
        '404':
          description: Документ не найден
        '500':
          description: Ошибка сервера
  /api/auth/{token}:
    delete:
      summary: Завершение сессии работы
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Сессия завершена
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: object
                    properties:
                      success:
                        type: boolean
              example:
                response:
                  success: true
        '400':
          description: Неверный запрос
          content:
            application/json:
              example:
                message: "Некорректный запрос"
        '500':
          description: Ошибка сервера
          content:
            application/json:
              example:
                message: "Ошибка сервера"